config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'boards#index'

  resources :boards do
    resources :tasks do
      resources :comments, only: [:new, :create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_boards_on_user_id  (user_id)
#
class Board < ApplicationRecord
  validates :title, presence: true
  validates :title, length: { minimum: 2, maximum: 100 }
  validates :title, format: { with: /\A(?!\@)/ }
  validates :content, presence: true
  validates :content, length: { minimum: 5 }
  validates :content, uniqueness: true

  validate :validate_title_and_content_length

  belongs_to :user
  has_many :tasks, dependent: :destroy

  private
  def validate_title_and_content_length
    char_count = self.title.length + self.content.length
    errors.add(:content, '10文字以上で作成してください')  unless char_count > 10
  end
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  task_id    :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_comments_on_task_id  (task_id)
#  index_comments_on_user_id  (user_id)
#
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :task
  validates :content, presence: true
  validates :content, length: { minimum: 2 }
  validates :content, uniqueness: true
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  deadline   :datetime
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_tasks_on_board_id  (board_id)
#  index_tasks_on_user_id   (user_id)
#
class Task < ApplicationRecord
  validates :title, presence: true
  validates :title, length: { minimum: 2, maximum: 100 }
  validates :content, presence: true
  validates :content, length: { minimum: 5 }
  validates :content, uniqueness: true

  has_one_attached :eyecatch

  has_many :comments, dependent: :destroy

  belongs_to :user
  belongs_to :board

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :comments, dependent: :destroy

  def has_written?(board)
    boards.exists?(id: board.id)
  end

  def has_written_task?(task)
    tasks.exists?(id: task.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
    before_action :set_board, only: [:edit, :update]

    def index
        @boards = Board.all
    end

    def show
        @board = Board.find(params[:id])
        @tasks = Task.where(board_id: @board.id)
    end

    def new
        @board = current_user.boards.build
    end

    def create
        @board = current_user.boards.build(board_params)
        if @board.save
            redirect_to board_path(@board), notice: '保存できました'
        else
            flash.now[:error] = '保存できませんでした'
            render :new
        end
    end

    def edit
    end

    def update
        if @board.update(board_params)
            redirect_to board_path(@board), notice: '更新できました'
        else
            flash.now[:error] = '更新できませんでした'
            render :edit
        end
    end

    def destroy
        board = current_user.boards.find(params[:id])
        board.destroy!
        redirect_to root_path, notice: '削除しました'
    end

    private
    def board_params
        params.require(:board).permit(:title, :content)
    end

    def set_board
        @board = current_user.boards.find(params[:id])
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_board, only: [:new, :create]

  def new
    task = @board.tasks.find(params[:task_id])
    @comment = task.comments.build(user: current_user)
  end

  def create
    task = @board.tasks.find(params[:task_id])
    @comment = task.comments.build(comment_params.merge(user: current_user))
    if @comment.save
      redirect_to board_task_path(@board, task), notice: 'コメントを追加'
    else
      flash.now[:error] = '更新できませんでした'
      render :new
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_board
    @board = Board.find(params[:board_id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_board, only: [:show, :new, :create, :edit, :update]
  before_action :set_task, only: [:edit, :update]

  def index
    @tasks = Tasks.all
  end

  def show
    @tasks = @board.tasks.find(params[:id])
    @comments = @tasks.comments
  end

  def new
    @task = @board.tasks.build(user: current_user)
  end

  def create
    @task = @board.tasks.build(task_params.merge(user: current_user))
    if @task.save
      redirect_to board_path(@board), notice: '保存できました'
    else
      flash.now[:error] = '保存できませんでした'
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to board_task_path(@board, @task), notice: '更新できました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

  def destroy
    board = Board.find(params[:board_id])
    task = board.tasks.find(params[:id])
    task.destroy!
    redirect_to board_path(board), notice: '削除しました'
  end

  private
  def task_params
    params.require(:task).permit(:title, :content, :deadline, :eyecatch)
  end

  def set_board
    @board = Board.find(params[:board_id])
  end

  def set_task
    @task = @board.tasks.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_board.html.haml
.card
  .card_text
    = link_to board_path(board) do
      .card_title 
        = board.title
      .card_content
        = board.content
      .card_image
        = image_tag 'default-user.png', class: 'user_avatar dropbtn'
  - if user_signed_in? && current_user.has_written?(board)
    .card_nav
      .card_btn
        = image_tag 'combined-shape.png', class: 'combined_shaped_btn dropbtn'
      .dropdown-content.mini
        = link_to 'Edit', edit_board_path(board)
        = link_to 'Delete', board_path(board), data: { method: 'delete', confirm: '本当に削除していいですか？' }

app/views/boards/_form.html.haml
.container
  %ul
    - board.errors.full_messages.each do |message|
      %li= message
  %h2 New Board
  = form_with(model: board, local: true) do |f|
    %div
      = f.label :title, 'Name'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, 'Description'
    %div
      = f.text_area :content
    = f.submit 'submit', class: 'btn-primary'

app/views/boards/_task.html.haml
.card
  .card_text
    = link_to board_task_path(@board, task) do
      - if task.eyecatch.attached?
        .eyecatch_image
          = image_tag task.eyecatch, class: 'eyecatch_image'
      .card_title
        = task.title
      .card_content 
        = task.content
      .card_image
        = image_tag 'default-user.png', class: 'user_avatar dropbtn'

app/views/boards/edit.html.haml
=render 'form', board: @board

app/views/boards/index.html.haml
.container
  %h2.card-logo All Boards
  - @boards.each do |board|
    =render 'board', board: board
  .newboard
    %p= link_to '+Add new board', new_board_path

app/views/boards/new.html.haml
=render 'form', board: @board

app/views/boards/show.html.haml
.container 
  %h2.card-logo Brackets
  .card_task
    .card_text
      .card_title 
      = @board.title
    .card_content
      = @board.content
    .card_image
      = image_tag 'default-user.png', class: 'user_avatar dropbtn'
  - @tasks.each do |task|
    =render 'task', task: task
  .newtask 
    %p= link_to '+Add new card', new_board_task_path(@board)

app/views/comments/new.html.haml
.container 
  %ul
    - @comment.errors.full_messages.each do |message|
      %li= message 
  %h2 New Comment 
  = form_with(model: @comment, url: board_task_comments_path(@board, @comment.task), method: 'post', local: true) do |f|
    %div
      =f.text_area :content
    = f.submit 'submit', class: 'btn-primary'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RanoTodoApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
  
  %body
    %header.header
      .header_logos
        - if !current_page?(root_path)
          = link_to :back do
            = image_tag 'back.png', class: 'header_back'
        %p.header-logo= link_to 'Boards', root_path, class: 'header-logo-link'
      - if user_signed_in?
        .dropdown
          = image_tag 'default-avatar.png', class: 'header_avatar dropbtn'
          .dropdown-content
            = link_to 'ログアウト', destroy_user_session_path, data: { method: 'delete'}
      - if flash.present?
        .flash 
          - flash.each do |key, value|
            .key{class: "%= %"}= value
    = yield
    -# %p.notice= notice
    -# %p.alert= alert

app/views/tasks/_comment.html.haml
.comment-text
  .comment-avatar
    = image_tag 'default-avatar.png', class: 'header_avatar dropbtn'
  .comment-content 
    %p= comment.content

app/views/tasks/_form.html.haml
.container
  %ul
    - task.errors.full_messages.each do |message|
      %li= message
  %h2 New Card
  = form_with(model: [board, task], local: true) do |f|
    %div
      = f.label :title, 'Name'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, 'Description'
    %div
      = f.text_area :content
    %div
      = f.label :eyectch, 'アイキャッチ'
    %div
      = f.file_field :eyecatch, class: 'file_field'
    = f.submit 'submit', class: 'btn-primary'

app/views/tasks/_task.html.haml
.task_header
  %h2.task-logo 
    = tasks.title
  - if user_signed_in? && current_user.has_written_task?(tasks)
    .card_nav 
      .card_btn 
        = image_tag 'combined-shape.png', class: 'combined_shaped_btn dropbtn'
      .dropdown-content.mini
        =link_to 'Edit', edit_board_task_path(board, tasks)
        =link_to 'Delete', board_task_path(board, tasks), data: { method: 'delete', confirm: '本当に削除していいですか？' }
.card_text
  - if tasks.eyecatch.attached?
    .eyecatch_image
      = image_tag tasks.eyecatch, class: 'eyecatch_image'
.card
  .card_content.task-card
    = tasks.content
%p.comment-logo Comment 

app/views/tasks/edit.html.haml
=render 'form', board: @board, task: @task

app/views/tasks/new.html.haml
=render 'form', board: @board, task: @task

app/views/tasks/show.html.haml
.container
  =render 'task', tasks: @tasks, board: @board
  - @comments.each do |comment|
    =render 'comment', comment: comment
  .newcomment 
    %p= link_to '+Add new comment', new_board_task_comment_path(@board, @tasks)